/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.wizardtest.testdemo2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Vacation generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`Vacation`")
public class Vacation implements Serializable {

    private Integer vacId;
    private Date startDate;
    private Date endDate;
    private String status;
    private String comments;
    private Integer empId;
    private Employee employee;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`VacID`", nullable = false, scale = 0, precision = 10)
    public Integer getVacId() {
        return this.vacId;
    }

    public void setVacId(Integer vacId) {
        this.vacId = vacId;
    }

    @Column(name = "`StartDate`", nullable = true)
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Column(name = "`EndDate`", nullable = true)
    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Column(name = "`Status`", nullable = true, length = 255)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "`Comments`", nullable = true, length = 255)
    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    @Column(name = "`EmpID`", nullable = true, scale = 0, precision = 10)
    public Integer getEmpId() {
        return this.empId;
    }

    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`EmpID`", referencedColumnName = "`EmpID`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_Employee_TO_Vacation_mBM0d`"))
    @Fetch(FetchMode.JOIN)
    public Employee getEmployee() {
        return this.employee;
    }

    public void setEmployee(Employee employee) {
        if(employee != null) {
            this.empId = employee.getEmpId();
        }

        this.employee = employee;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Vacation)) return false;
        final Vacation vacation = (Vacation) o;
        return Objects.equals(getVacId(), vacation.getVacId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getVacId());
    }
}