/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.wizardtest.rndpp;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SiteMaster generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`SiteMaster`")
public class SiteMaster implements Serializable {

    private Integer siteId;
    private String siteName;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`SiteID`", nullable = false, scale = 0, precision = 10)
    public Integer getSiteId() {
        return this.siteId;
    }

    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    @Column(name = "`SiteName`", nullable = true, length = 255)
    public String getSiteName() {
        return this.siteName;
    }

    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SiteMaster)) return false;
        final SiteMaster siteMaster = (SiteMaster) o;
        return Objects.equals(getSiteId(), siteMaster.getSiteId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSiteId());
    }
}